SRC += features/secrets.c
SRC += caracarn.c
SRC += features/achordion.c
SRC += definitions/keycodes.c
SRC += features/caps_word.c
SRC += features/taphold.c
SRC += features/default_mod_key.c
SRC += features/capitalize_key.c
SRC += features/tapdance.c
SRC += features/capslock_timer.c
SRC += features/os_toggle.c
SRC += features/macros.c
SRC += features/combos.c
SRC += features/leader.c
SRC += features/select_word.c
SRC += features/window_swapper.c
SRC += features/custom_shortcuts.c
SRC += features/custom_shift.c

RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
AUDIO_ENABLE = no          # Audio output
LEADER_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio control and System control
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = yes
BACKLIGHT_ENABLE = no
SWAP_HANDS_ENABLE = no
KEY_LOCK_ENABLE = no
MAGIC_ENABLE = no

