RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
AUDIO_ENABLE = no          # Audio output
MUSIC_ENABLE = no
CONSOLE_ENABLE = yes
BACKLIGHT_ENABLE = no
SWAP_HANDS_ENABLE = no
KEY_LOCK_ENABLE = no
MAGIC_ENABLE = no


#Custom Features
LEADER_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio control and System control
TAP_DANCE_ENABLE = yes
SECRETS_ENABLE = yes
ACHORDION_ENABLE = yes
CAPSWORD_ENABLE = yes
TAPHOLD_ENABLE = yes
DEFAULT_MOD_KEY_ENABLE = yes
CAPITALIZE_KEY_ENABLE = yes
CAPSLOCK_TIMER_ENABLE = yes
OS_TOGGLE_ENABLE = yes
MACRO_ENABLE = yes
SELECT_WORD_ENABLE = yes
WINDOW_SWAPPER_ENABLE = yes
SHORTCUTS_ENABLE = yes
CUSTOM_SHIFT_ENABLE = yes
